export const STATUS_APPLICATION_NOT_READY = 0
export const STATUS_CATEGORIES_NO_DATA = -1
export const STATUS_PRODUCTS_NO_DATA = -1

export const STATUS_CATEGORIES_DATA_READY = 1
export const STATUS_PRODUCTS_DATA_READY = 2
