export const STATUS_PRODUCTS_SAVING = "STATUS_PRODUCTS_SAVING "// constants
export const STATUS_PRODUCTS_PURCHASE_POSSIBLE = "STATUS_PRODUCTS_PURCHASE_POSSIBLE"
export const STATUS_PRODUCTS_NO_PRODUCTS = "STATUS_PRODUCTS_NO_PRODUCTS"